### ISSUE TITLE
docker-compose error: host not found in upstream "django:8000"

### ISSUE THREAD

**Issue by kaustubhharapanahalli** [MausamGaurav/DockerDjangoReactProject#1]
Hello,

I am trying to build an application using Docker. To get a reference, I tried to run your app on my Windows laptop.
I ran
- `docker-compose build`
and after that,
- `docker-compose up`

The command `docker-compose up` works, but nginx is giving an error saying:
```
nginx_1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1   | 10-listen-on-ipv6-by-default.sh: /etc/nginx/conf.d/default.conf is not a file or does not exist, exiting
nginx_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1   | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1   | 2020/09/18 05:19:47 [emerg] 1#1: host not found in upstream "django:8000" in /etc/nginx/conf.d/nginx.conf:2

nginx_1   | nginx: [emerg] host not found in upstream "django:8000" in /etc/nginx/conf.d/nginx.conf:2
```

Is it possible for you to help regarding this issue?
Thanks in advance

**Comment by kaustubhharapanahalli** [comment]
I had not seen that I need to use dos2unix on entrypoint. Now all the dockers are running, but when I navigate to http://127.0.0.1 browser is throwing HTTP Error 404. The requested resource is not found.

Any idea why this is happening?

**Comment by MausamGaurav** [comment]
You need to change the EOL formatting for the entrypoint.sh. Please read the article. https://towardsdatascience.com/build-a-fully-production-ready-machine-learning-app-with-python-django-react-and-docker-c4d938c251e5

**Comment by MausamGaurav** [comment]
The other way is to remove, the entry point.sh and perform the commands manually on the django container when it's running
