### ISSUE TITLE
React not able to find static file 

### ISSUE THREAD

**Issue by zzakeer** [MausamGaurav/DockerDjangoReactProject#3]
Hi Mausam,

Thanks for this project. It helped me a lot in setting up the project.(react + Django +docker )

It works fine for the first-time deployment.
but I have found some issue when any changes made for react code and I try to run a command 
1) docker-compose build and docker-compose up
both backend and frontend server runs up. 
But when I browse http://localhost it shows me a white screen with an error in the console. 
which I have shared an error screenshot. 
https://paste.pics/a2858dfe65fba4968eb87c70669f5678

I think the issue is in this file 
https://github.com/MausamGaurav/DockerDjangoReactProject/blob/master/frontend/Dockerfile
because it does not generate static files and save in react static volume 

Thanks and regards 
Abdul Waheed

**Comment by MausamGaurav** [comment]
This is because of how docker-compose works. Please research properly before opening an issue. There is no issue anywhere in the code.  And I am not obliged to answer everyone's questions.
