### ISSUE TITLE
problems with connecting to postgres

### ISSUE THREAD

**Issue by michalstepniewski** [MausamGaurav/DockerDjangoReactProject#4]
django_1  | django.db.utils.OperationalError: could not connect to server: Connection refused
django_1  | 	Is the server running on host "127.0.0.1" and accepting
django_1  | 	TCP/IP connections on port 5432?

**Comment by MausamGaurav** [comment]
How is this an issue? Clearly, your Postgres service/container has died due to some reason. Please perform some troubleshooting and investigation before opening as an issue.

**Comment by michalstepniewski** [comment]
sorry I fixed this
