### ISSUE TITLE
CORS rejecting api calls

### ISSUE THREAD

**Issue by SwiftPredator** [MausamGaurav/DockerDjangoReactProject#5]
I tried to setup the project following the tutorial and i also tried to setup the project directly from this repo. 
It seems like cors blocks all requests to the Django backend. After some research, i think it's because of Nginx, because Django's setup should be correct. I've tested your project on a mac os system and this is the error message in chrome:
`Access to XMLHttpRequest at 'http://127.0.0.1/api/auth/logout/' from origin 'http://localhost:84' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

The only thing i changed is the port mapping from 80 to 84, since 80 was already used in my case. 
I tried to add the headers manually in the nginx config file, but it didn't help, unfortunately. 
Maybe someone had the same issue and found a solution?

**Comment by magedhelmy1** [comment]
I changed nginx to "FROM nginx:1.21-alpine" and I used incognito web and they seemed to fix my issue.
